ERROR - 2022-12-11 04:58:56 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=27596 in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171)
#1 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\test\app\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\test\app\Controllers\User.php(22): App\Models\ModelUser->AllData()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\User->index()
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\User.php(22): App\Models\ModelUser->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\User->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\test\app\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\test\app\Controllers\User.php(22): App\Models\ModelUser->AllData()
#5 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\User->index()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-12-11 04:58:56 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=27596 in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171)
#1 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#9 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#5 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-12-11 04:58:56 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=27596 in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171)
#1 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\test\app\Models\ModelPembelian.php(13): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\test\app\Controllers\Pembelian.php(23): App\Models\ModelPembelian->AllData()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Pembelian->index()
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pembelian))
#9 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelPembelian.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\Pembelian.php(23): App\Models\ModelPembelian->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Pembelian->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pembelian))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\test\app\Models\ModelPembelian.php(13): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\test\app\Controllers\Pembelian.php(23): App\Models\ModelPembelian->AllData()
#5 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Pembelian->index()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pembelian))
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-12-11 04:58:56 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=27596 in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171)
#1 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#9 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#5 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 04:58:56 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `pembelian`', [], false)
 3 APPPATH\Models\ModelPembelian.php(13): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Pembelian.php(23): App\Models\ModelPembelian->AllData()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Pembelian->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pembelian))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 04:58:56 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `penjualan`', [], false)
 3 APPPATH\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Penjualan->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 04:58:56 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `penjualan`', [], false)
 3 APPPATH\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Penjualan->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 04:58:56 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`', [], false)
 3 APPPATH\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\User.php(22): App\Models\ModelUser->AllData()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 04:59:09 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\User.php(22): App\Models\ModelUser->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\User->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\test\app\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\test\app\Controllers\User.php(22): App\Models\ModelUser->AllData()
#5 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\User->index()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 04:59:09 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`', [], false)
 3 APPPATH\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\User.php(22): App\Models\ModelUser->AllData()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 05:03:18 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\User.php(22): App\Models\ModelUser->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\User->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\test\app\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\test\app\Controllers\User.php(22): App\Models\ModelUser->AllData()
#5 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\User->index()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 05:03:18 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`', [], false)
 3 APPPATH\Models\ModelUser.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\User.php(22): App\Models\ModelUser->AllData()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 05:24:02 --> mysqli_sql_exception: Table 'harmonis.penjualan' doesn't exist in engine in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-11 05:24:02 --> Table 'harmonis.penjualan' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `penjualan`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `penjualan`')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `penjualan`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `penjualan`', [], false)
 5 APPPATH\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Penjualan->index()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 06:12:12 --> mysqli_sql_exception: Table 'harmonis.penjualan' doesn't exist in engine in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-11 06:12:12 --> Table 'harmonis.penjualan' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `penjualan`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `penjualan`')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `penjualan`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `penjualan`', [], false)
 5 APPPATH\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Penjualan->index()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-11 06:14:43 --> mysqli_sql_exception: Table 'harmonis.penjualan' doesn't exist in engine in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-11 06:14:43 --> Table 'harmonis.penjualan' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `penjualan`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `penjualan`')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `penjualan`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `penjualan`', [], false)
 5 APPPATH\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Penjualan->index()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 19:46:51 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:46:52 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:50:25 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:50:26 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:50:26 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:51:57 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:51:58 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:51:58 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:52:10 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-12-11 19:52:10 --> Class 'Locale' not found
in SYSTEMPATH\CodeIgniter.php on line 186.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2022-12-11 12:53:00 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'harmonis' in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'harmonis', 3306, '', 0)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#8 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'harmonis' in C:\xampp\htdocs\test\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\test\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\test\app\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\test\app\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
#5 C:\xampp\htdocs\test\system\CodeIgniter.php(927): App\Controllers\Penjualan->index()
#6 C:\xampp\htdocs\test\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
#7 C:\xampp\htdocs\test\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-12-11 12:53:00 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'harmonis'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `penjualan`', [], false)
 3 APPPATH\Models\ModelPenjualan.php(13): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Penjualan.php(23): App\Models\ModelPenjualan->AllData()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Penjualan->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 12:57:12 --> Division by zero
in APPPATH\Views\penjualan.php on line 54.
 1 APPPATH\Views\penjualan.php(54): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Division by zero', 'APPPATH\\Views\\penjualan.php', 54, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\penjualan.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('penjualan', [], true)
 5 APPPATH\Views\template.php(168): view('penjualan')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\template.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('template', [], true)
 9 APPPATH\Controllers\Penjualan.php(25): view('template', [...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Penjualan->index()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Penjualan))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-11 12:59:50 --> Undefined index: id_user
in APPPATH\Views\user.php on line 51.
 1 APPPATH\Views\user.php(51): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: id_user', 'APPPATH\\Views\\user.php', 51, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\user.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('user', [], true)
 5 APPPATH\Views\template.php(168): view('user')
 6 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\template.php')
 7 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('template', [], true)
 9 APPPATH\Controllers\User.php(24): view('template', [...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\User->index()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
